class AppConstants {
  static const String localConfig = 'local_config';
  static const String remoteConfig = 'remote_config';
  static const String movie = 'movie';
  static const String tvShow = 'tv';
  static const String person = 'person';
  static const String personalInfo = 'personal_info';
  static const String credits = 'credits';
  static const String sortBy = 'sort_by';
  static const String genres = 'genres';
  static const String popular = 'popular';
  static const String currentlyPlaying = 'currently_playing';
  static const String topRated = 'Top Rated';
  static const String latest = 'Latest';
  static const String upcoming = 'Upcoming';
  static const String nowPlaying = 'Now Playing';
  static const String airingToday = 'Airing Today';
  static const String onTheAir = 'On The Air';
  static const String suggestions = 'suggestions';
  static const String search = 'search';
  static const String progress = 'progress';
  static const String yearFormat = 'yyyy';
  static const String dateFormat = 'dd-MM-yyyy';
  static const String NA = 'NA';
  static const String trailer = 'Trailer';
  static const List<String> movieSortByList = ['Upcoming', 'Now Playing', 'Latest', 'Top Rated'];
  static const List<String> showSortByList = ['Airing Today', 'On The Air', 'Latest', 'Top Rated'];
  static const int maxPages = 500;
}